name: Release 

on: 
  push: 
    branches:
      - master

jobs:
  github_release:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Tag commit and release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v0.8.1
        commit: master
        name: Gitrise v0.8.1
        bodyFile: ./docs/release_notes/v0.8.1.md